### ISSUE TITLE
`kp builder create` should have better support for the Buildpack resource

### ISSUE THREAD

**Issue by chenbh** [buildpacks-community/kpack-cli#340]
There's no way to pass in object references to Buildpack and ClusterBuildpacks.

It also automatically assumes a ClusterStore is used and still creates a block for it even if `--store=""` is used:
```yaml
spec:
  ...
  store:
    kind: ClusterStore
```
