### ISSUE TITLE
The `--store` flag on `kp builder create` should be optional

### ISSUE THREAD

**Issue by chenbh** [buildpacks-community/kpack-cli#341]
Because the Builder/ClusterBuilder could be using the Buildpack and ClusterBuildpack resources instead

Right now, even if I pass `--store=""`, it still creates a block for the clusterstore:
```yaml
spec:
  ...
  store:
    kind: ClusterStore
```
